import { ObjectType, Field, registerEnumType } from '@nestjs/graphql';
import { Schema, SchemaFactory, Prop } from '@nestjs/mongoose';
import { Document } from 'mongoose';
import { SimulationResult } from './result.model';

/** Different layouts supported by COMETS */
export enum LayoutType {
  PETRI_CENTER = 'petri_center',
  PETRI_RANDOM = 'petri_random',
  TEST_TUBE = 'test_tube'
}
registerEnumType(LayoutType, {
  name: 'LayoutType'
});

/** The GraphQL representation of layout parameters */
@ObjectType()
export class LayoutParameters {
  @Prop({ type: String, enum: LayoutType })
  @Field(() => LayoutType)
  type: LayoutType;

  @Prop()
  @Field()
  volume: number;
}

/** Different metabolites supported by COMETS */
export enum MetaboliteType {
  GLUCOSE = 'glc__D_e',
  ACETATE = 'ac_e',
  RICH = 'rich'
}
registerEnumType(MetaboliteType, {
  name: 'MetaboliteType'
});

/** The GraphQL representation of metabolite parameters */
@ObjectType()
export class MetaboliteParameters {
  @Prop({ type: String, enum: MetaboliteType })
  @Field(() => MetaboliteType)
  type: MetaboliteType;

  @Prop()
  @Field()
  concentration: number;
}
export const MetaboliteParametersSchema = SchemaFactory.createForClass(MetaboliteParameters);

/** Different models supported by COMETS */
export enum ModelName {
  E_COLI = 'escherichia coli core',
  NITROSOMONAS = 'nitrosomonas europaea',
  NITROBACTER = 'nitrobacter winogradskyi'
}
registerEnumType(ModelName, {
  name: 'ModelName'
});

/** The GraphQL representation of model parameters */
@ObjectType()
@Schema()
export class ModelParameters {
  @Prop({ type: String, enum: ModelName })
  @Field(() => ModelName)
  name: ModelName;

  @Prop()
  @Field()
  neutralDrift: boolean;

  @Prop()
  @Field()
  neutralDriftAmp: number;

  @Prop()
  @Field()
  deathRate: number;

  @Prop()
  @Field()
  linearDiffusivity: number;

  @Prop()
  @Field()
  nonlinearDiffusivity: number;
}
export const ModelParametersSchema = SchemaFactory.createForClass(ModelParameters);

/** The GraphQL representation of global parameters */
@ObjectType()
@Schema()
export class GlobalParameters {
  @Prop()
  @Field()
  timeStep: number;

  @Prop()
  @Field()
  logFreq: number;

  @Prop()
  @Field()
  defaultDiffConst: number;

  @Prop()
  @Field()
  defaultVMax: number;

  @Prop()
  @Field()
  defaultKm: number;

  @Prop()
  @Field()
  maxCycles: number;
}
export const GlobalParametersSchema = SchemaFactory.createForClass(GlobalParameters);

/** Represents the state of the simulation */
export enum SimulationStatus {
  SUCCESS = 'success',
  IN_PROGRESS = 'in progress',
  FAILED = 'failed'
}
registerEnumType(SimulationStatus, {
  name: 'SimulationStatus'
});

/** The GraphQL representation of the request the user made */
@Schema()
@ObjectType()
export class SimulationRequest {
  /** Unique ID generated by MongoDB */
  @Field()
  _id: string;

  /** The requesting user's email for sending results */
  @Prop()
  @Field(() => String)
  email: string;

  /** The layout parameters */
  @Prop()
  @Field(() => LayoutParameters)
  layoutParams: LayoutParameters;

  /** The metabolite parameters */
  @Prop({ type: MetaboliteParameters })
  @Field(() => MetaboliteParameters)
  metaboliteParams: MetaboliteParameters;

  /** The model parameters */
  @Prop({ type: [ModelParameters] })
  @Field(() => [ModelParameters])
  modelParams: ModelParameters[];

  /** The global parameters */
  @Prop({ type: GlobalParameters })
  @Field(() => GlobalParameters)
  globalParams: GlobalParameters;

  /** The status of the simulation request */
  @Prop({ type: String, enum: SimulationStatus })
  @Field(() => SimulationStatus)
  status: SimulationStatus;

  /** The results from the simulation, added in once the simulation has finished, null before then */
  @Prop({ type: SimulationResult, required: false })
  @Field(() => SimulationResult, { nullable: true })
  result: SimulationResult | null;
}

export type SimulationRequestDocument = SimulationRequest & Document;
export const SimulationRequestSchema = SchemaFactory.createForClass(SimulationRequest);
